/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulaval.ui;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JTextField;
import ulaval.models.Key;
import ulaval.models.MidiInstrument;

/**
 *
 * @author alexis
 */
public class PropertyBar extends javax.swing.JPanel {

    JColorChooser ColorChooser = null;
    
    Key key = null;
    
    JButton SaveColorButton = null;
    
    JButton CancelColorButton = null;
    
    JPanel jFileChooserPanel = null;
    
    JFileChooser FileChooser = null;
    
    /**
     * Creates new form NavBar
     */
    public PropertyBar() {
        initComponents();
        DefaultComboBoxModel<String> combo = new DefaultComboBoxModel<>();
        for (MidiInstrument midi : MidiInstrument.values()) {
            combo.addElement(midi.name());
        }
        ToneList.setModel(combo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DefaultPropertyPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PrintLabelCheckBox = new javax.swing.JCheckBox();
        ToneLabelField = new javax.swing.JTextField();
        SizePanel = new javax.swing.JPanel();
        HeightLabel = new javax.swing.JLabel();
        HeightTextField = new javax.swing.JTextField();
        TonePlusTopButton = new javax.swing.JButton();
        ToneMinusTopButton = new javax.swing.JButton();
        ToneMinusRightButton = new javax.swing.JButton();
        TonePlusRightButton = new javax.swing.JButton();
        WidthTextField = new javax.swing.JTextField();
        WidthLabel = new javax.swing.JLabel();
        BorderPanel = new javax.swing.JPanel();
        BorderSizeLabel = new javax.swing.JLabel();
        BorderSizeTextField = new javax.swing.JTextField();
        OpenColorChooserBorderPanel = new javax.swing.JButton();
        BorderColorLabel = new javax.swing.JLabel();
        ShowBordureLeft = new javax.swing.JCheckBox();
        ShowBordureDown = new javax.swing.JCheckBox();
        ShowBordureRight = new javax.swing.JCheckBox();
        ShowBorudureUp = new javax.swing.JCheckBox();
        ButtonDeleteKey = new javax.swing.JButton();
        BackgroundPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        OpenColorChooserPanel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PictureLabel = new javax.swing.JLabel();
        SongPanel = new javax.swing.JPanel();
        SampleTextField = new javax.swing.JTextField();
        SampleOpenFileButton = new javax.swing.JButton();
        PersistanceLabel1 = new javax.swing.JLabel();
        PersistanceLabel = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        ToneList = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        DefaultPropertyPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Key Properties", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Display Name :");

        PrintLabelCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        PrintLabelCheckBox.setName("PrintLabelCheckBox"); // NOI18N
        PrintLabelCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintLabelCheckBoxActionPerformed(evt);
            }
        });

        ToneLabelField.setName("DisplayNameTextField"); // NOI18N

        SizePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Size", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 14))); // NOI18N

        HeightLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        HeightLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HeightLabel.setText("Height (px):");

        HeightTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HeightTextField.setName("HeightTextField"); // NOI18N

        TonePlusTopButton.setBackground(new java.awt.Color(102, 204, 255));
        TonePlusTopButton.setText("+");
        TonePlusTopButton.setName("TonePlusTopButton"); // NOI18N

        ToneMinusTopButton.setBackground(new java.awt.Color(102, 204, 255));
        ToneMinusTopButton.setText("-");
        ToneMinusTopButton.setName("ToneMinusTopButton"); // NOI18N

        ToneMinusRightButton.setBackground(new java.awt.Color(102, 204, 255));
        ToneMinusRightButton.setText("-");
        ToneMinusRightButton.setName("ToneMinusRightButton"); // NOI18N

        TonePlusRightButton.setBackground(new java.awt.Color(102, 204, 255));
        TonePlusRightButton.setText("+");
        TonePlusRightButton.setName("TonePlusRightButton"); // NOI18N

        WidthTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WidthTextField.setName("WidthTextField"); // NOI18N

        WidthLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        WidthLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        WidthLabel.setText("Width (px) :");

        javax.swing.GroupLayout SizePanelLayout = new javax.swing.GroupLayout(SizePanel);
        SizePanel.setLayout(SizePanelLayout);
        SizePanelLayout.setHorizontalGroup(
            SizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SizePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HeightLabel)
                    .addComponent(WidthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HeightTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(WidthTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TonePlusTopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TonePlusRightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ToneMinusTopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ToneMinusRightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SizePanelLayout.setVerticalGroup(
            SizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SizePanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(SizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HeightLabel)
                    .addComponent(HeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TonePlusTopButton)
                    .addComponent(ToneMinusTopButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TonePlusRightButton)
                    .addComponent(ToneMinusRightButton)
                    .addComponent(WidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WidthLabel))
                .addContainerGap())
        );

        ToneMinusTopButton.getAccessibleContext().setAccessibleParent(ToneMinusTopButton);
        ToneMinusRightButton.getAccessibleContext().setAccessibleParent(ToneMinusRightButton);
        TonePlusRightButton.getAccessibleContext().setAccessibleParent(TonePlusRightButton);

        BorderPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Border", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 14))); // NOI18N

        BorderSizeLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        BorderSizeLabel.setText("Size :");

        BorderSizeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BorderSizeTextField.setName("SizeBorderTextField"); // NOI18N

        OpenColorChooserBorderPanel.setText("...");
        OpenColorChooserBorderPanel.setName("BorderColorButton"); // NOI18N
        OpenColorChooserBorderPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenColorChooserBorderPanelActionPerformed(evt);
            }
        });

        BorderColorLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        BorderColorLabel.setText("Color :");

        ShowBordureLeft.setName("ShowBordureLeft"); // NOI18N

        ShowBordureDown.setName("ShowBordureDown"); // NOI18N

        ShowBordureRight.setName("ShowBordureRight"); // NOI18N

        ShowBorudureUp.setName("ShowBordureUp"); // NOI18N

        javax.swing.GroupLayout BorderPanelLayout = new javax.swing.GroupLayout(BorderPanel);
        BorderPanel.setLayout(BorderPanelLayout);
        BorderPanelLayout.setHorizontalGroup(
            BorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorderPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ShowBordureLeft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowBordureDown)
                    .addComponent(ShowBorudureUp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowBordureRight)
                .addGap(18, 18, 18)
                .addGroup(BorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BorderColorLabel)
                    .addComponent(BorderSizeLabel))
                .addGap(18, 18, 18)
                .addGroup(BorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BorderSizeTextField)
                    .addComponent(OpenColorChooserBorderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        BorderPanelLayout.setVerticalGroup(
            BorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorderPanelLayout.createSequentialGroup()
                .addGroup(BorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(BorderPanelLayout.createSequentialGroup()
                            .addComponent(ShowBorudureUp)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ShowBordureDown))
                        .addGroup(BorderPanelLayout.createSequentialGroup()
                            .addGroup(BorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BorderSizeLabel)
                                .addComponent(BorderSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(BorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(OpenColorChooserBorderPanel)
                                .addComponent(BorderColorLabel))))
                    .addGroup(BorderPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(BorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ShowBordureRight)
                            .addComponent(ShowBordureLeft))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ButtonDeleteKey.setBackground(new java.awt.Color(255, 51, 51));
        ButtonDeleteKey.setText("Delete");
        ButtonDeleteKey.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true)));
        ButtonDeleteKey.setName("DeleteKey"); // NOI18N

        BackgroundPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Background", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 14))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Color :");

        OpenColorChooserPanel.setText("...");
        OpenColorChooserPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenColorChooserPanelActionPerformed(evt);
            }
        });

        jButton1.setText("...");
        jButton1.setName("OpenFileChooser"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("x");

        PictureLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        PictureLabel.setText("Picture :");

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OpenColorChooserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addComponent(PictureLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(OpenColorChooserPanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(PictureLabel))
                .addGap(6, 6, 6))
        );

        SongPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Song", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 14))); // NOI18N

        SampleTextField.setName("SampleTextField"); // NOI18N

        SampleOpenFileButton.setText("...");
        SampleOpenFileButton.setName("OpenSampleFileChooser"); // NOI18N

        PersistanceLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        PersistanceLabel1.setText("Or Sample :");

        PersistanceLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        PersistanceLabel.setText("Persistance (ms) :");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("500");
        jTextField2.setName("PersistanceTextField"); // NOI18N

        ToneList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ToneList.setName("ToneList"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Instrument :");

        jTextField1.setName("SetToneTextField"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Tone :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G" }));
        jComboBox1.setMinimumSize(new java.awt.Dimension(52, 26));
        jComboBox1.setName("ToneValue"); // NOI18N

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBox2.setName("OctaveValue"); // NOI18N
        jComboBox2.setPreferredSize(new java.awt.Dimension(52, 26));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "b", "#" }));
        jComboBox3.setName("OtherValue"); // NOI18N
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SongPanelLayout = new javax.swing.GroupLayout(SongPanel);
        SongPanel.setLayout(SongPanelLayout);
        SongPanelLayout.setHorizontalGroup(
            SongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SongPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SongPanelLayout.createSequentialGroup()
                        .addGroup(SongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SongPanelLayout.createSequentialGroup()
                                .addGroup(SongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SongPanelLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(SongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ToneList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(SongPanelLayout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(SongPanelLayout.createSequentialGroup()
                        .addGroup(SongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SongPanelLayout.createSequentialGroup()
                                .addComponent(PersistanceLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SampleOpenFileButton))
                            .addComponent(PersistanceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2)
                            .addComponent(SampleTextField))))
                .addContainerGap())
        );
        SongPanelLayout.setVerticalGroup(
            SongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SongPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(SongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ToneList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PersistanceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PersistanceLabel1)
                    .addComponent(SampleOpenFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SampleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setText("Disable Move Key : ");

        jCheckBox1.setName("MoveCheckBox"); // NOI18N

        javax.swing.GroupLayout DefaultPropertyPanelLayout = new javax.swing.GroupLayout(DefaultPropertyPanel);
        DefaultPropertyPanel.setLayout(DefaultPropertyPanelLayout);
        DefaultPropertyPanelLayout.setHorizontalGroup(
            DefaultPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SizePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BorderPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SongPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DefaultPropertyPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PrintLabelCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ToneLabelField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DefaultPropertyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addGap(24, 24, 24)
                .addComponent(ButtonDeleteKey, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        DefaultPropertyPanelLayout.setVerticalGroup(
            DefaultPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DefaultPropertyPanelLayout.createSequentialGroup()
                .addGroup(DefaultPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DefaultPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PrintLabelCheckBox)
                        .addComponent(ToneLabelField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SongPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SizePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BorderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DefaultPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonDeleteKey, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DefaultPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jCheckBox1)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DefaultPropertyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DefaultPropertyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OpenColorChooserPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenColorChooserPanelActionPerformed
        // TODO add your handling code here:
        if (ColorChooser != null) {
            if (ColorChooser.isVisible()) {
                ColorChooser.setVisible(false);
                SaveColorButton.setVisible(false);
                CancelColorButton.setVisible(false);
            } else {
                ColorChooser.setVisible(true);
                SaveColorButton.setVisible(true);
                CancelColorButton.setVisible(true);
            }
        }
    }//GEN-LAST:event_OpenColorChooserPanelActionPerformed

    private void OpenColorChooserBorderPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenColorChooserBorderPanelActionPerformed
        // TODO add your handling code here:
        if (ColorChooser != null) {
            //System.out.println("open ColorChooser");
            if (ColorChooser.isVisible()) {
                ColorChooser.setVisible(false);
                SaveColorButton.setVisible(false);
                CancelColorButton.setVisible(false);
            } else {
                ColorChooser.setVisible(true);
                SaveColorButton.setVisible(true);
                CancelColorButton.setVisible(true);
            }
            if (key != null) {
                //System.out.println("");
            }
        }
    }//GEN-LAST:event_OpenColorChooserBorderPanelActionPerformed

    private void PrintLabelCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintLabelCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintLabelCheckBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel BorderColorLabel;
    private javax.swing.JPanel BorderPanel;
    private javax.swing.JLabel BorderSizeLabel;
    private javax.swing.JTextField BorderSizeTextField;
    private javax.swing.JButton ButtonDeleteKey;
    private javax.swing.JPanel DefaultPropertyPanel;
    private javax.swing.JLabel HeightLabel;
    private javax.swing.JTextField HeightTextField;
    private javax.swing.JButton OpenColorChooserBorderPanel;
    private javax.swing.JButton OpenColorChooserPanel;
    private javax.swing.JLabel PersistanceLabel;
    private javax.swing.JLabel PersistanceLabel1;
    private javax.swing.JLabel PictureLabel;
    private javax.swing.JCheckBox PrintLabelCheckBox;
    private javax.swing.JButton SampleOpenFileButton;
    private javax.swing.JTextField SampleTextField;
    private javax.swing.JCheckBox ShowBordureDown;
    private javax.swing.JCheckBox ShowBordureLeft;
    private javax.swing.JCheckBox ShowBordureRight;
    private javax.swing.JCheckBox ShowBorudureUp;
    private javax.swing.JPanel SizePanel;
    private javax.swing.JPanel SongPanel;
    private javax.swing.JTextField ToneLabelField;
    private javax.swing.JComboBox<String> ToneList;
    private javax.swing.JButton ToneMinusRightButton;
    private javax.swing.JButton ToneMinusTopButton;
    private javax.swing.JButton TonePlusRightButton;
    private javax.swing.JButton TonePlusTopButton;
    private javax.swing.JLabel WidthLabel;
    private javax.swing.JTextField WidthTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    JTextField getSampleTextField() {
        return this.SampleTextField;
    }
}
